# include "benchmarks/list.ispc"
# include "benchmarks/matrix.ispc"
# include "benchmarks/memorycopy.ispc"


// ----------------------------------------------------------------------------
// LDP[1]: context mask usage
export void ldp_contextmask() {
}

// ----------------------------------------------------------------------------
// LDP[2]: using shuffle instruction
export void ldp_shuffle() {
}
